# Generated by Django 4.2.1 on 2023-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameguide',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
