# Generated by Django 4.2.1 on 2023-06-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_gameguide_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameguide',
            name='created_at',
        ),
    ]
