# Generated by Django 4.1.6 on 2023-02-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_answer_message_newsblog_review_remove_game_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='cetegory',
            field=models.ManyToManyField(to='home.category'),
        ),
    ]
