# Generated by Django 4.2.1 on 2023-06-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_content_receiver',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_content_sender',
            field=models.TextField(null=True),
        ),
    ]
