# Generated by Django 4.2 on 2023-05-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0002_remove_user_name_user_username_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, limit_choices_to=5, to='games.game'),
        ),
    ]
