# Generated by Django 4.2 on 2023-05-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_favorite_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pseudo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
