# Generated by Django 4.2.1 on 2023-05-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='big_size_avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='small_size_avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
