# Generated by Django 4.2.1 on 2023-05-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_big_size_avatar_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
