# Generated by Django 4.2.1 on 2023-06-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
