# Generated by Django 4.2.1 on 2023-06-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privat_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
