# Generated by Django 4.2.1 on 2023-06-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_privat_key_user_public_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='privat_key',
            new_name='private_key',
        ),
    ]
